-- 1. VAICAJUMS 1. VARIANTS
SELECT 
    'AAA emitenti' AS Kategorija,
    ROUND(AVG(CalculateBondPrice_1(o.OBLIGACIJAS_ID)), 2) AS VIDEJA_OBLIGACIJU_CENA
FROM 
    OBLIGACIJAS_1 o
JOIN 
    EMITENTI_1 e ON o.EMITENTA_ID = e.EMITENTA_ID
WHERE 
    e.KREDITA_REITINGS = 'AAA'

UNION ALL

SELECT 
    'Visas oblig?cijas' AS Kategorija,
    ROUND(AVG(CalculateBondPrice_1(o.OBLIGACIJAS_ID)), 2) AS VIDEJA_OBLIGACIJAS
FROM 
    OBLIGACIJAS_1 o
JOIN 
    EMITENTI_1 e ON o.EMITENTA_ID = e.EMITENTA_ID;

-- 1. VAICAJUMS 2. VARIANTS
SELECT 
    'AAA emitenti' AS Kategorija,
    ROUND(AVG(CalculateBondPrice_1(o.OBLIGACIJAS_ID)), 2) AS VIDEJA_OBLIGACIJU_CENA
FROM 
    OBLIGACIJAS_1 o
JOIN 
    EMITENTI_1 e ON o.EMITENTA_ID = e.EMITENTA_ID
WHERE 
    e.KREDITA_REITINGS = 'AAA'

UNION ALL

SELECT 
    'Visas oblig?cijas' AS Kategorija,
    ROUND(AVG(o.CalculateBondPrice_2()), 2) AS VIDEJA_OBLIGACIJAS
FROM 
    OBLIGACIJAS_2 o;
    
    
-- 2. VAICAJUMS 1. VARIANTS
SELECT 
    EMITENTI_1.KREDITA_REITINGS,
    COUNT(OBLIGACIJAS_1.OBLIGACIJAS_ID) AS OBLIGACIJAS_SKAITS,
    ROUND(AVG(CalculateBondPrice_1(OBLIGACIJAS_1.OBLIGACIJAS_ID)), 2) AS VIDEEJA_VERTIBA,
    SUM(OBLIGACIJAS_1.NOMINALA_VERTIBA) AS KOPUMA_NOMINALA_VERTIBA,
    ROUND(
        (COUNT(DISTINCT OBLIGACIJAS_1.EMITENTA_ID) / 
         (SELECT COUNT(DISTINCT EMITENTA_ID) FROM EMITENTI_1)) * 100, 2
    ) AS PROCENTU_NO_VISIEM_EMITENTIEM
FROM 
    OBLIGACIJAS_1
JOIN 
    EMITENTI_1 ON OBLIGACIJAS_1.EMITENTA_ID = EMITENTI_1.EMITENTA_ID
GROUP BY 
    EMITENTI_1.KREDITA_REITINGS
ORDER BY 
    CASE KREDITA_REITINGS
        WHEN 'AAA' THEN 1
        WHEN 'AA' THEN 2
        WHEN 'A' THEN 3
        WHEN 'BBB' THEN 4
        WHEN 'BB' THEN 5
        WHEN 'B' THEN 6
        WHEN 'CCC' THEN 7
        WHEN 'CC' THEN 8
        WHEN 'C' THEN 9
        WHEN 'D' THEN 10
        ELSE 11
    END;

-- 2. VAICAJUMS 2. VARIANTS
SELECT 
    E.KREDITA_REITINGS,
    COUNT(O.OBLIGACIJAS_ID) AS OBLIGACIJAS_SKAITS,
    ROUND(AVG(O.CalculateBondPrice_2()), 2) AS VIDEEJA_VERTIBA,
    SUM(O.NOMINALA_VERTIBA) AS KOPUMA_NOMINALA_VERTIBA,
    ROUND(
        (COUNT(DISTINCT DEREF(O.EMITENTS_REF).EMITENTA_ID) / 
         (SELECT COUNT(DISTINCT E2.EMITENTA_ID) FROM EMITENTI_2 E2)) * 100, 2
    ) AS PROCENTU_NO_VISIEM_EMITENTIEM
FROM 
    OBLIGACIJAS_2 O,
    EMITENTI_2 E
WHERE 
    DEREF(O.EMITENTS_REF).EMITENTA_ID = E.EMITENTA_ID
GROUP BY 
    E.KREDITA_REITINGS
ORDER BY 
    CASE E.KREDITA_REITINGS
        WHEN 'AAA' THEN 1
        WHEN 'AA' THEN 2
        WHEN 'A' THEN 3
        WHEN 'BBB' THEN 4
        WHEN 'BB' THEN 5
        WHEN 'B' THEN 6
        WHEN 'CCC' THEN 7
        WHEN 'CC' THEN 8
        WHEN 'C' THEN 9
        WHEN 'D' THEN 10
        ELSE 11
    END;
    
-- 3. VAICAJUMS 1. VARIANTS
SELECT 
    e.KREDITA_REITINGS,
    ROUND(AVG(o.KUPONS), 2) as AVG_KUPONA_LIKME,
    ROUND(AVG(CalculateBondPrice_1(o.OBLIGACIJAS_ID)), 2) as VIDEJA_VERTIBA,
    COUNT(o.OBLIGACIJAS_ID) as OBLIGACIJU_SKAITS
FROM EMITENTI_1 e
INNER JOIN OBLIGACIJAS_1 o ON e.EMITENTA_ID = o.EMITENTA_ID
WHERE o.DZESANAS_DATUMS >= TO_DATE('2018-01-01', 'YYYY-MM-DD')
    AND e.EMITENTA_ID IN (
        SELECT EMITENTA_ID 
        FROM OBLIGACIJAS_1 
        GROUP BY EMITENTA_ID 
        HAVING COUNT(*) > 1
    )
GROUP BY e.KREDITA_REITINGS
ORDER BY AVG_KUPONA_LIKME DESC;

-- 3. VAICAJUMS 2. VARIANTS
SELECT 
    e.KREDITA_REITINGS,
    ROUND(AVG(o.KUPONS), 2) as AVG_KUPONA_LIKME,
    ROUND(AVG(o.CalculateBondPrice_2()), 2) as VIDEJA_VERTIBA,
    COUNT(o.OBLIGACIJAS_ID) as OBLIGACIJU_SKAITS
FROM EMITENTI_2 e
INNER JOIN OBLIGACIJAS_2 o ON REF(e) = o.EMITENTS_REF
WHERE o.DZESANAS_DATUMS >= TO_DATE('2018-01-01', 'YYYY-MM-DD')
    AND e.EMITENTA_ID IN (
        SELECT DEREF(ob.EMITENTS_REF).EMITENTA_ID 
        FROM OBLIGACIJAS_2 ob
        GROUP BY DEREF(ob.EMITENTS_REF).EMITENTA_ID
        HAVING COUNT(*) > 1
    )
GROUP BY e.KREDITA_REITINGS
ORDER BY AVG_KUPONA_LIKME DESC;
