INSERT INTO EMITENTI_2
SELECT Emitents(EMITENTA_ID, NOSAUKUMS, KREDITA_REITINGS)
FROM EMITENTI_1;

INSERT INTO OBLIGACIJAS_2
SELECT Obligacija(
    O.OBLIGACIJAS_ID,
    O.NOMINALA_VERTIBA,
    O.KUPONS,
    O.DZESANAS_DATUMS,
    REF(E)
)
FROM OBLIGACIJAS_1 O, EMITENTI_2 E
WHERE O.EMITENTA_ID = E.EMITENTA_ID;